branches:
  only:
  - master
language: go
install: go get github.com/spf13/hugo

before_script:
  - chmod +x ./_deploy.sh

script:
  - hugo

deploy:
  provider: script
  script: ./_deploy.sh
  skip_cleanup: true
