################################# Default configuration ###################
baseURL = "https://139bercy.github.io/hub/"
languageCode = "fr-fr"
title = "MEF >> SG >> DSI >> Hub"
theme = "meghna-hugo"
# post pagination
#paginate = "6"
# post excerpt
#summaryLength = "15"
# disqus short name
#disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
#disableLanguages = []

############################# Plugins ##########################
# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/animate-css/animate.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap"

# js plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/wow/wow.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"


############################# Navigation ##################################
[[menu.main]]
name = "Valeurs"
URL = "about"
weight = 2

[[menu.main]]
name = "Services"
URL = "services"
weight = 3

[[menu.main]]
name = "Portfolio"
URL = "portfolio"
weight = 4

[[menu.main]]
name = "Equipe"
URL = "our-team"
weight = 5

[[menu.main]]
name = "Blog"
URL = "blog"
weight = 7

[[menu.main]]
name = "Contact"
URL = "contact-us"
weight = 8

############################# Default Parameters ##########################
[params]
logo = "images/logo.png"
# Meta data
description = "Bercy hub"
author = "Themefisher"
# Google Analitycs
google_analitycs_id = "UA-158047494-1" # Your ID
# post share
post_share = true

# preloader
[params.preloader]
enable = true
preloader = "images/logo.png"

# google map
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "48.8402778"
map_longitude = "2.3777777777"
map_marker = "images/marker.png"

################################ English Language ########################
[Languages.en]
languageName = "Fr"
languageCode = "fr-fr"
contentDir = "content/french"
weight = 1
home = "Accueil"